### ISSUE TITLE
Make min sdk version required to 8

### ISSUE THREAD

**Issue by shivamsingh** [pwittchen/prefser#10]

**Comment by pwittchen** [comment]
I'll check if it's possible to set min sdk to 8 and eventually update it to make Prefser accessible on older devices. Nevertheless, min sdk = 15 is recommended for new apps and this library has even older version - min sdk = 11.

**Comment by pwittchen** [comment]
Changing min sdk version to 8 is not possible, because library uses [apply()](http://developer.android.com/reference/android/content/SharedPreferences.Editor.html#apply()) method from SharedPreferences for saving data, which is available from sdk 9. I'll change min sdk to 9 (Android 2.3). It's the lowest API, which Prefser can use.

**Comment by pwittchen** [comment]
Min sdk = 9 will be available in version 1.0.2 of the library.
